package com.msamil.msamilkotlinquizz.util

import android.widget.Button
import com.msamil.msamilkotlinquizz.R

class selectedButton {
    fun btn( i:Int,btn1:Button,btn2:Button,btn3:Button,btn4:Button,btn5:Button,btn6:Button,btn7:Button,btn8:Button,btn9:Button,btn10:Button){
        if (i == 1){
            btn1.setBackgroundResource(R.drawable.custom_btn3)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        } else if (i ==2){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn3)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==3){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn3)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==4){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn3)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==5){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn3)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==6){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn3)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==7){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn3)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==8){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn3)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==9){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn3)
            btn10.setBackgroundResource(R.drawable.custom_btn2)
        }else if (i ==10){
            btn1.setBackgroundResource(R.drawable.custom_btn2)
            btn2.setBackgroundResource(R.drawable.custom_btn2)
            btn3.setBackgroundResource(R.drawable.custom_btn2)
            btn4.setBackgroundResource(R.drawable.custom_btn2)
            btn5.setBackgroundResource(R.drawable.custom_btn2)
            btn6.setBackgroundResource(R.drawable.custom_btn2)
            btn7.setBackgroundResource(R.drawable.custom_btn2)
            btn8.setBackgroundResource(R.drawable.custom_btn2)
            btn9.setBackgroundResource(R.drawable.custom_btn2)
            btn10.setBackgroundResource(R.drawable.custom_btn3)
        }
    }
}